
simulation: &simulation
  name: ''
  kind: 'dynamic'
  parameters:
    configuration:
      timespan: 5000
      machines_per_work_center: 1
      work_center_count: 10
      pre_assign_initial_jobs: True

    job_sampler:
      kind: 'dynamic'
      parameters:
        processing_times: # Sampler
          kind: 'uniform'
          parameters:
            uniform: [ 10, 30 ]
            noise: [ 0, 3 ]
        permutation:
          uneveness: 5
        due_time: # Sampler
          kind: 'uniform'
          parameters:
            uniform: [ 0, 0.2 ]
        job_arrival_time_on_machine:
          kind: 'sampler'
          parameters:
            sampler:
              kind: 'uniform'
              parameters:
                uniform: [ 1, 10 ]

    breakdown:
      kind: 'dynamic'
      parameters:
        breakdown_arrival:
          kind: 'exponential'
          parameters:
              mean: 1000
        repair_duration:
          kind: 'uniform'
          parameters:
              uniform: [ 200, 500 ]

    seed: 42

task:
  kind: 'task'

  machine_agent:
    kind: 'dqn'
    parameters:
      model:
        kind: 'multi_rule_linear'
        parameters:
          rules: 'all'
          nn:
            layers:
              - kind: 'instance_norm'
              - kind: 'linear'
                parameters:
                  dim: 48
                  activation: 'tanh'
              - kind: 'linear'
                parameters:
                  dim: 36
                  activation: 'tanh'
              - kind: 'linear'
                parameters:
                  dim: 36
                  activation: 'tanh'
              - kind: 'linear'
                parameters:
                  dim: 24
                  activation: 'tanh'
              - kind: 'linear'
                parameters:
                  dim: 12
                  activation: 'tanh'
          action_selector:
            kind: 'phase_selector'
            parameters:
              default:
                kind: 'greedy'
              phases:
                - phase:
                    kind: 'training'
                  action_selector:
                    kind: 'epsilon_greedy'
                    parameters:
                      epsilon: 0.95
                - phase:
                    kind: 'warm_up'
                    parameters:
                      step: 0
                  action_selector:
                    kind: 'uniform'
                - phase:
                    kind: 'warm_up'
                    parameters:
                      step: 1
                  action_selector:
                    kind: 'uniform'

      encoder:
        kind: 'deep_marl_indirect'

      memory:
        kind: 'replay'
        parameters:
          size: 8192
          batch_size: 64

      loss:
        kind: 'mse'

      optimizer:
        kind: 'adam'
        parameters:
          lr: 0.001

      parameters:
        gamma: 0.4

  work_center_agent:
    kind: 'static'
    parameters:
      model:
        kind: 'static'
        parameters:
          rule: 'random'
      encoder:
        kind: 'plain'

  tape:
    machine_reward:
      kind: 'global_tardiness'

    work_center_reward:
      kind: 'no'

  simulator:
    kind: 'td'

  run:
    timeline:
      warmup:
        - 1000
        - 1000

      duration: 10000

    machine_train_schedule:
      pretrain_steps: 10
      train_interval: 100
      max_training_steps: 1000

    work_center_train_schedule:
      pretrain_steps: 10
      train_interval: 100
      max_training_steps: 1000

    n_workers: 2
    simulations:
      - <<: *simulation
      - <<: *simulation
      - <<: *simulation
      - <<: *simulation

  evaluate:
    n_workers: 2
    simulations:
      - <<: *simulation
